In [6]:
import torch
import torch.nn as nn
import math

In [2]:
empty_edge = torch.empty([2,0])

In [8]:
empty_edge.size()[-1]

0

In [21]:
out = torch.rand((10,))

In [23]:
out

tensor([0.6613, 0.4862, 0.8549, 0.2677, 0.6530, 0.4645, 0.9764, 0.0092, 0.5679,
        0.3295])

In [24]:
torch.max(out,torch.ones_like(out))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
out.shape[0]

10

In [ ]:
# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()

In [33]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()


In [36]:
input.shape

torch.Size([3, 5])

In [37]:
target.shape

torch.Size([3])

In [39]:
a = 5
print([a]*3)
print(list(a)*3)

[5, 5, 5]


TypeError: 'int' object is not iterable

### check RTE

In [7]:
class RelTemporalEncoding(torch.nn.Module):
    '''
        Implement the Temporal Encoding (Sinusoid) function.
    '''
    def __init__(self, n_hid, max_len = 240, dropout = 0.2):
        super(RelTemporalEncoding, self).__init__()
        position = torch.arange(0., max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, n_hid, 2) *
                             -(math.log(10000.0) / n_hid))
        emb = torch.nn.Embedding(max_len, n_hid)
        emb.weight.data[:, 0::2] = torch.sin(position * div_term) / math.sqrt(n_hid)
        emb.weight.data[:, 1::2] = torch.cos(position * div_term) / math.sqrt(n_hid)
        emb.requires_grad = False
        self.emb = emb
        self.lin = torch.nn.Linear(n_hid, n_hid)
    def forward(self, x, t):
        return x + self.lin(self.emb(t))

In [8]:
rte_demo = RelTemporalEncoding(8, max_len=240)

In [10]:
x = torch.rand((4,8))
# torch.randint(0, 10, (train_data[edge_type].edge_index.shape[1],))
t = torch.randint(0,10, (100,))

In [11]:
print(x)
print(t)

tensor([[0.3419, 0.1724, 0.8794, 0.1805, 0.6367, 0.8786, 0.4847, 0.4033, 0.3627,
         0.0651, 0.8484, 0.3934, 0.6713, 0.4728, 0.8684, 0.8350, 0.6461, 0.4703,
         0.0780, 0.6583, 0.8922, 0.3320, 0.7128, 0.5840, 0.1269, 0.2986, 0.3927,
         0.2269, 0.5518, 0.2041, 0.8701, 0.3334],
        [0.5457, 0.0906, 0.1986, 0.8647, 0.8991, 0.4514, 0.3768, 0.8098, 0.4270,
         0.7941, 0.7921, 0.9265, 0.4659, 0.3243, 0.9277, 0.6922, 0.5995, 0.5037,
         0.1172, 0.5404, 0.5202, 0.2461, 0.1997, 0.6897, 0.2523, 0.8349, 0.0773,
         0.8354, 0.2820, 0.1057, 0.9695, 0.5245],
        [0.2007, 0.3608, 0.3463, 0.1313, 0.2004, 0.1293, 0.9450, 0.5048, 0.7932,
         0.8472, 0.3210, 0.2177, 0.2689, 0.1598, 0.6896, 0.3532, 0.7103, 0.0499,
         0.9913, 0.1060, 0.9154, 0.4942, 0.0910, 0.2656, 0.1752, 0.2661, 0.1413,
         0.4761, 0.8279, 0.0202, 0.6336, 0.8701],
        [0.5691, 0.7189, 0.6576, 0.2433, 0.2988, 0.3667, 0.7556, 0.8899, 0.3737,
         0.0473, 0.9424, 0.3372, 0.1814,

In [12]:
rte_demo(x,t)

RuntimeError: The size of tensor a (32) must match the size of tensor b (8) at non-singleton dimension 1